### ISSUE TITLE
Windows call should use the Roaming folder

### ISSUE THREAD

**Issue by sago007** [zchee/go-xdgbasedir#1]
As mentioned on http://doc.qt.io/qt-5/qstandardpaths.html the DataLocation value is deprecated in favour of the roaming folder (AppDataLocation).
```
ConfigDirs()
ConfigHome()
DataHome()
DataDirs()
```
should use:
```
C:/Users/<USER>/AppData/Roaming
```
In corporate environment "C:/Users/<USER>/AppData/Local" may be purged from time to time and will be skipped in backups. It should only be used for cache.

**Comment by zchee** [comment]
@sago007 Wow, thanks advice and suggestion :)

Yeah, I also referred QT's `enum QStandardPaths::StandardLocation`.
I will following that deprecated spec and fix some codes.
Very thanks 👍

**Comment by zchee** [comment]
Close via https://github.com/zchee/go-xdgbasedir/commit/49c1524f6676fd7ef0692a8c457b7d441df159bd.
